KindTransaction.create(description: 'Débito', nature: 1, signal: 1)
KindTransaction.create(description: 'Boleto', nature: 0, signal: 0)
KindTransaction.create(description: 'Financiamento', nature: 0, signal: 0)
KindTransaction.create(description: 'Crédito', nature: 1, signal: 1)
KindTransaction.create(description: 'Recebimento Empréstimo', nature: 1, signal: 1)
KindTransaction.create(description: 'Vendas', nature: 1, signal: 1)
KindTransaction.create(description: 'Recebimento TED', nature: 1, signal: 1)
KindTransaction.create(description: 'Recebimento DOC', nature: 1, signal: 1)
KindTransaction.create(description: 'Aluguel', nature: 0, signal: 0)
